# Generated by Django 4.1.5 on 2023-07-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0002_imagesofmountains_remove_mountain_other_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain',
            old_name='author',
            new_name='user',
        ),
    ]
